### ISSUE TITLE
Product id '544ad5cb-7e52-4a30-b1d7-a080abafbfac' no longer being updated due to unsuported endpoint version

### ISSUE THREAD

**Issue by VivekGeorge** [LukePrior/open-banking-tracker#2]
This product id: 544ad5cb-7e52-4a30-b1d7-a080abafbfac gives this message in the latest nighly release:

{
    "errors": [
        {
            "detail": "Unable to select an endpoint version. Supported versions: min = 4, max = 4.",
            "title": "Unsupported Version",
            "code": "urn:au-cds:error:cds-all:Header/UnsupportedVersion"
        }
    ]
}

**Comment by LukePrior** [comment]
There was a few issues with the API, I have updated these now.

**Comment by VivekGeorge** [comment]
Thanks @LukePrior, would that mean any historical data for that product Id be incomplete?

**Comment by LukePrior** [comment]
Yes unfortunately the historical data is complete for the period of time where the incorrect API version was used.
